---
- hosts: localhost
  become: yes
  tasks: 
  - name: create ansible ubuntu nodes
    ec2:
      key_name: myUbuntu
      instance-type: t2.micro
      image: myansible_Ubuntu_AMI
      wait: yes
      region: us-east-2
      group: launch-wizard-8
      count: 2
      vpc_subnet_id: subnet-2029796c
      assign_public_ip: yes
      instance_tags:
        name: myansibleUbuntuNode
